version: '3.7'

services: 
  
  nginx:
    image: nginx:latest
    container_name: khaning_nginx
    ports:
        - 80:80
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - .:/var/www/html/
    environment:
      - NGINX_HOST=khaning.test
      - NGINX_PORT=80
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/softwindev.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
        - wordpress
    restart: "no"
    # docker run --name some-wordpress --link=some-mysql:mysql -e WORDPRESS_DB_NAME=some_wordpress -v /var/docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini -v /var/docker/phpinfo.php:/var/www/html/phpinfo.php -p 8081:80  -d wordpress
  wordpress:
    image: wordpress:5.6.1-php7.4-fpm
    depends_on:
      - mysql
    container_name: khaning_wordpress
    restart: "no"
    ports:
      - 9000:9000
    working_dir: /var/www/html
    restart: on-failure:5
    volumes:
      - .:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:     
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: khaning-database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: S@Wa2d2e0506
      WORDPRESS_TABLE_PREFIX: khaning_
      WORDPRESS_DEBUG: 1 
  
  cli:
   image: wordpress:cli
   container_name: khaning_cli
   volumes:
     - .:/var/www/html/

  mysql:
    image: mariadb:10.5.8-focal
    container_name: khaning_mysql
    restart: "no"
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: khaning-database
      MYSQL_ROOT_PASSWORD: S@Wa2d2e0506
      MYSQL_USER: root
      MYSQL_PASSWORD: S@Wa2d2e0506
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: khaning_phpmyadmin
    environment:
      - PMA_HOST=khaning_mysql
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=S@Wa2d2e0506
    restart: "no"
    ports:
      - 8090:80
    volumes:
      - /sessions
    depends_on:
      - mysql
    
volumes:
  db_data: